changes README example to not throw
error from ASCIIString[msg] is:

ERROR: LoadError: MethodError: `convert` has no method matching convert(::Type{ASCIIString}, ::ZMQ.Message)
This may have arisen from a call to the constructor ASCIIString(...),
since type constructors fall back to convert methods.
Closest candidates are:
  call{T}(::Type{T}, ::Any)
  convert(::Type{ASCIIString}, !Matched::ASCIIString)