Qualify which brew formula to use
This fix avoids a potential conflict when updating an existing ZMQ
instance which has tapped the default homebrew formula previously, e.g.:

```jl
julia> Pkg.build("IJulia")
INFO: Building Homebrew
Already up-to-date.
INFO: Building Nettle
INFO: Building ZMQ
Error: Formulae found in multiple taps:
 * homebrew/versions/zeromq32
 * staticfloat/juliadeps/zeromq32

Please use the fully-qualified name e.g. homebrew/versions/zeromq32 to
refer the formula.
```